-- Oracle Database / PL/SQL schema for RailReserve
-- Run in SQL Developer or SQL*Plus as the application schema owner.

CREATE TABLE passenger (
  passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(100) NOT NULL, date_of_birth DATE, gender VARCHAR2(10),
  phone VARCHAR2(20) NOT NULL UNIQUE, email VARCHAR2(120) UNIQUE,
  id_type VARCHAR2(30) NOT NULL, id_number VARCHAR2(50) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT ck_passenger_gender CHECK (gender IN ('MALE','FEMALE','OTHER') OR gender IS NULL)
);
CREATE TABLE train (
  train_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  train_number VARCHAR2(10) NOT NULL UNIQUE, train_name VARCHAR2(100) NOT NULL,
  source_station VARCHAR2(80) NOT NULL, destination_station VARCHAR2(80) NOT NULL,
  distance_km NUMBER(7,2) NOT NULL, departure_time VARCHAR2(5) NOT NULL,
  arrival_time VARCHAR2(5) NOT NULL, active NUMBER(1) DEFAULT 1 NOT NULL
);
CREATE TABLE train_service (
  service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  train_id NUMBER NOT NULL REFERENCES train(train_id), journey_date DATE NOT NULL,
  service_status VARCHAR2(12) DEFAULT 'SCHEDULED' NOT NULL,
  CONSTRAINT uq_train_service UNIQUE (train_id, journey_date),
  CONSTRAINT ck_service_status CHECK (service_status IN ('SCHEDULED','CANCELLED','COMPLETED'))
);
CREATE TABLE class_inventory (
  inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id NUMBER NOT NULL REFERENCES train_service(service_id), travel_class VARCHAR2(4) NOT NULL,
  total_seats NUMBER(5) NOT NULL, available_seats NUMBER(5) NOT NULL,
  base_rate_per_km NUMBER(8,2) NOT NULL,
  CONSTRAINT uq_service_class UNIQUE (service_id, travel_class),
  CONSTRAINT ck_seat_count CHECK (available_seats BETWEEN 0 AND total_seats)
);
CREATE TABLE ticket (
  ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pnr VARCHAR2(12) NOT NULL UNIQUE, passenger_id NUMBER NOT NULL REFERENCES passenger(passenger_id),
  service_id NUMBER NOT NULL REFERENCES train_service(service_id), travel_class VARCHAR2(4) NOT NULL,
  booking_status VARCHAR2(12) NOT NULL, seat_number VARCHAR2(10), waitlist_number NUMBER(5),
  fare NUMBER(10,2) NOT NULL, booked_at TIMESTAMP DEFAULT SYSTIMESTAMP, cancelled_at TIMESTAMP,
  CONSTRAINT ck_ticket_status CHECK (booking_status IN ('CONFIRMED','WAITLIST','CANCELLED'))
);
CREATE INDEX ix_ticket_waitlist ON ticket(service_id, travel_class, booking_status, waitlist_number);

CREATE OR REPLACE FUNCTION calculate_fare(p_service_id NUMBER, p_travel_class VARCHAR2)
RETURN NUMBER IS
  v_distance train.distance_km%TYPE; v_rate class_inventory.base_rate_per_km%TYPE;
BEGIN
  SELECT tr.distance_km, ci.base_rate_per_km INTO v_distance, v_rate
  FROM train_service ts JOIN train tr ON tr.train_id = ts.train_id
  JOIN class_inventory ci ON ci.service_id = ts.service_id
  WHERE ts.service_id = p_service_id AND ci.travel_class = UPPER(p_travel_class);
  RETURN ROUND((v_distance * v_rate + 25) * 1.05, 2);
EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20001, 'Invalid service or travel class');
END;
/

CREATE OR REPLACE TRIGGER ticket_inventory_change
AFTER INSERT OR UPDATE OF booking_status ON ticket FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.booking_status = 'CONFIRMED' THEN
    UPDATE class_inventory SET available_seats = available_seats - 1 WHERE service_id = :NEW.service_id AND travel_class = :NEW.travel_class;
  ELSIF UPDATING AND :OLD.booking_status <> 'CONFIRMED' AND :NEW.booking_status = 'CONFIRMED' THEN
    UPDATE class_inventory SET available_seats = available_seats - 1 WHERE service_id = :NEW.service_id AND travel_class = :NEW.travel_class;
  ELSIF UPDATING AND :OLD.booking_status = 'CONFIRMED' AND :NEW.booking_status = 'CANCELLED' THEN
    UPDATE class_inventory SET available_seats = available_seats + 1 WHERE service_id = :NEW.service_id AND travel_class = :NEW.travel_class;
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE promote_waitlist(p_service_id NUMBER, p_travel_class VARCHAR2) IS
  v_available NUMBER; v_ticket_id NUMBER;
BEGIN
  SELECT available_seats INTO v_available FROM class_inventory WHERE service_id = p_service_id AND travel_class = UPPER(p_travel_class) FOR UPDATE;
  WHILE v_available > 0 LOOP
    BEGIN
      SELECT ticket_id INTO v_ticket_id FROM (
        SELECT ticket_id FROM ticket WHERE service_id = p_service_id AND travel_class = UPPER(p_travel_class) AND booking_status = 'WAITLIST'
        ORDER BY waitlist_number) WHERE ROWNUM = 1 FOR UPDATE;
    EXCEPTION WHEN NO_DATA_FOUND THEN EXIT; END;
    UPDATE ticket SET booking_status = 'CONFIRMED', seat_number = UPPER(p_travel_class) || '-' || v_available, waitlist_number = NULL WHERE ticket_id = v_ticket_id;
    v_available := v_available - 1;
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE book_ticket(p_passenger_id NUMBER, p_service_id NUMBER, p_travel_class VARCHAR2,
  p_pnr OUT VARCHAR2, p_status OUT VARCHAR2, p_fare OUT NUMBER) IS
  v_available NUMBER; v_service_status VARCHAR2(12); v_waitlist NUMBER;
BEGIN
  SELECT service_status INTO v_service_status FROM train_service WHERE service_id = p_service_id FOR UPDATE;
  IF v_service_status <> 'SCHEDULED' THEN RAISE_APPLICATION_ERROR(-20002, 'Service is unavailable for booking'); END IF;
  SELECT available_seats INTO v_available FROM class_inventory WHERE service_id = p_service_id AND travel_class = UPPER(p_travel_class) FOR UPDATE;
  p_fare := calculate_fare(p_service_id, p_travel_class); p_pnr := 'PNR' || TO_CHAR(SYSTIMESTAMP, 'FF9');
  IF v_available > 0 THEN
    p_status := 'CONFIRMED';
    INSERT INTO ticket(pnr,passenger_id,service_id,travel_class,booking_status,seat_number,fare) VALUES(p_pnr,p_passenger_id,p_service_id,UPPER(p_travel_class),p_status,UPPER(p_travel_class)||'-'||v_available,p_fare);
  ELSE
    SELECT NVL(MAX(waitlist_number),0)+1 INTO v_waitlist FROM ticket WHERE service_id=p_service_id AND travel_class=UPPER(p_travel_class) AND booking_status='WAITLIST';
    p_status := 'WAITLIST';
    INSERT INTO ticket(pnr,passenger_id,service_id,travel_class,booking_status,waitlist_number,fare) VALUES(p_pnr,p_passenger_id,p_service_id,UPPER(p_travel_class),p_status,v_waitlist,p_fare);
  END IF;
  COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE cancel_ticket(p_pnr VARCHAR2) IS
  v_service_id NUMBER; v_class VARCHAR2(4); v_status VARCHAR2(12);
BEGIN
  SELECT service_id,travel_class,booking_status INTO v_service_id,v_class,v_status FROM ticket WHERE pnr=UPPER(p_pnr) FOR UPDATE;
  IF v_status='CANCELLED' THEN RAISE_APPLICATION_ERROR(-20003, 'Ticket is already cancelled'); END IF;
  UPDATE ticket SET booking_status='CANCELLED',seat_number=NULL,waitlist_number=NULL,cancelled_at=SYSTIMESTAMP WHERE pnr=UPPER(p_pnr);
  IF v_status='CONFIRMED' THEN promote_waitlist(v_service_id,v_class); END IF;
  COMMIT;
EXCEPTION WHEN NO_DATA_FOUND THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20004, 'PNR not found'); WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
